### ISSUE TITLE
KMP plugin 0.11.0 makes iOS build fail on GitHub Action workflow

### ISSUE THREAD

**Issue by franmontiel** [getsentry/sentry-kotlin-multiplatform#347]
### Platform

Apple

### Installed

Swift Package Manager

### Version

0.11.0 plugin

### Steps to Reproduce

This version allows me to build locally the iOS library without issues but makes the build fail on GitHub Actions with the following error:

> Plugin 'io.sentry.kotlin.multiplatform.gradle': failed to compute value with custom source 'io.sentry.kotlin.multiplatform.gradle.DerivedDataPathValueSource' with org.gradle.process.internal.ExecException: Process 'command 'xcodebuild'' finished with non-zero exit value 74

As a sample the "Build and Test" step of the following workflow is failing (it also fails if using `./gradlew iosSimulatorArm64TestBinaries` or `/gradlew linkDebugFrameworkIosSimulator`)
````
name: Build All Modules
on:
  pull_request:
    branches:
      - "**"

# Avoids running the same workflow concurrently for the same branch
concurrency:
  # Here the group is defined by the branch name
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  build-ios:
    name: Build & test iOS

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: "adopt"
          java-version: "17"
          architecture: "aarch64"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build and Test
        run: ./gradlew iosSimulatorArm64Test

env:
  GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx3g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=512m"
  ORG_GRADLE_PROJECT_CORIS_USERNAME: ${{ secrets.CORIS_USERNAME }}
  ORG_GRADLE_PROJECT_CORIS_PASSWORD: ${{ secrets.CORIS_PASSWORD }}

````

### Expected Result

The library builds correctly in the GitHub Actions environment (as it was doing until the usage of the Sentry plugin).

### Actual Result

The library does not compile
> Plugin 'io.sentry.kotlin.multiplatform.gradle': failed to compute value with custom source 'io.sentry.kotlin.multiplatform.gradle.DerivedDataPathValueSource' with org.gradle.process.internal.ExecException: Process 'command 'xcodebuild'' finished with non-zero exit value 74

Here the full stacktrace -> [sentry-github-actions-stacktrace.txt](https://github.com/user-attachments/files/19346347/sentry-github-actions-stacktrace.txt)
